"""小说创作流程提示词与常量"""
from .prompts import (
    ARCHIVER_SYSTEM,
    ARCHIVER_USER,
    BACKGROUND_SYSTEM,
    BACKGROUND_USER,
    OUTLINE_SYSTEM,
    OUTLINE_USER,
    POLISHER_SYSTEM,
    POLISHER_USER,
    ROLE_NAMES,
    WRITER_SYSTEM,
    WRITER_USER,
)

__all__ = [
    "ARCHIVER_SYSTEM",
    "ARCHIVER_USER",
    "BACKGROUND_SYSTEM",
    "BACKGROUND_USER",
    "OUTLINE_SYSTEM",
    "OUTLINE_USER",
    "POLISHER_SYSTEM",
    "POLISHER_USER",
    "ROLE_NAMES",
    "WRITER_SYSTEM",
    "WRITER_USER",
]
